# Generated by Django 5.0.6 on 2024-06-20 16:02

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('Image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=95, scale=None, size=[1200, 800], upload_to='gallery/%Y/%m')),
            ],
            options={
                'verbose_name': 'gallery',
                'verbose_name_plural': 'gallery',
                'db_table': 'gallery',
            },
        ),
    ]
