# Generated by Django 5.0.6 on 2024-06-25 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='massage',
            new_name='message',
        ),
    ]
