# Generated by Django 5.0.6 on 2024-06-25 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_rename_massage_contact_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='titl',
            new_name='title',
        ),
    ]
